export const ENLACES_LIST = [
    { muni: 'Medellin', dept: 'Antioquia' },
    { muni: 'Turbaco', dept: 'Bolivar' },
    { muni: 'Neira', dept: 'Caldas' },
    { muni: 'Gobernación', dept: 'Caldas' },
    { muni: 'Florencia', dept: 'Caquetá' },
    { muni: 'Albania', dept: 'Caquetá' },
    { muni: 'Cartagena del Chairá', dept: 'Caquetá' },
    { muni: 'Curillo', dept: 'Caquetá' },
    { muni: 'Gobernación', dept: 'Cauca' },
    { muni: 'Corinto', dept: 'Cauca' },
    { muni: 'La Sierra', dept: 'Cauca' },
    { muni: 'Mercaderes', dept: 'Cauca' },
    { muni: 'Popayan', dept: 'Cauca' },
    { muni: 'Rosas', dept: 'Cauca' },
    { muni: 'Santander de Quilichao', dept: 'Cauca' },
    { muni: 'Valledupar', dept: 'Cesar' },
    { muni: 'Agustín Codazzi', dept: 'Cesar' },
    { muni: 'Bosconia', dept: 'Cesar' },
    { muni: 'Istmina', dept: 'Chocó' },
    { muni: 'Bojayá', dept: 'Chocó' },
    { muni: 'Condoto', dept: 'Chocó' },
    { muni: 'Gobernación', dept: 'Córdoba' },
    { muni: 'Sahagún', dept: 'Córdoba' },
    { muni: 'El Rosal', dept: 'Cundinamarca' },
    { muni: 'Fusagasuga', dept: 'Cundinamarca' },
    { muni: 'Mosquera', dept: 'Cundinamarca' },
    { muni: 'Funza', dept: 'Cundinamarca' },
    { muni: 'Girardot', dept: 'Cundinamarca' },
    { muni: 'Guasca', dept: 'Cundinamarca' },
    { muni: 'Madrid', dept: 'Cundinamarca' },
    { muni: 'Ubate', dept: 'Cundinamarca' },
    { muni: 'Chía', dept: 'Cundinamarca' },
    { muni: 'Facatativá', dept: 'Cundinamarca' },
    { muni: 'Puerto Salgar', dept: 'Cundinamarca' },
    { muni: 'Soacha', dept: 'Cundinamarca' },
    { muni: 'Tabio', dept: 'Cundinamarca' },
    { muni: 'Gobernación', dept: 'Guaviare' },
    { muni: 'Ciénaga', dept: 'Magdalena' },
    { muni: 'Santa Marta', dept: 'Magdalena' },
    { muni: 'Granada', dept: 'Meta' },
    { muni: 'Cumaral', dept: 'Meta' },
    { muni: 'Gobernación', dept: 'Meta' },
    { muni: 'Guamal', dept: 'Meta' },
    { muni: 'Mesetas', dept: 'Meta' },
    { muni: 'Puerto López', dept: 'Meta' },
    { muni: 'Gobernación', dept: 'Norte Santander' },
    { muni: 'Armenia', dept: 'Quindío' },
    { muni: 'Gobernación', dept: 'Quindío' },
    { muni: 'Calarca', dept: 'Quindío' },
    { muni: 'Montenegro', dept: 'Quindío' },
    { muni: 'Salento', dept: 'Quindío' },
    { muni: 'Gobernación', dept: 'Risaralda' },
    { muni: 'Dosquebradas', dept: 'Risaralda' },
    { muni: 'La Virginia', dept: 'Risaralda' },
    { muni: 'Santa Rosa De Cabal', dept: 'Risaralda' },
    { muni: 'Santuario', dept: 'Risaralda' },
    { muni: 'Pereira', dept: 'Risaralda' },
    { muni: 'Cajamarca', dept: 'Tolima' },
    { muni: 'Chaparral', dept: 'Tolima' },
    { muni: 'Ibague', dept: 'Tolima' },
    { muni: 'Flandes', dept: 'Tolima' },
    { muni: 'Gobernación', dept: 'Tolima' },
    { muni: 'Lérida', dept: 'Tolima' },
    { muni: 'Villarrica', dept: 'Tolima' },
    { muni: 'Líbano', dept: 'Tolima' },
    { muni: 'Mariquita', dept: 'Tolima' },
    { muni: 'Melgar', dept: 'Tolima' },
    { muni: 'Buenaventura', dept: 'Valle del Cauca' },
    { muni: 'Cartago', dept: 'Valle del Cauca' },
    { muni: 'Pradera', dept: 'Valle del Cauca' },
    { muni: 'Trujillo', dept: 'Valle del Cauca' },
    { muni: 'Yumbo', dept: 'Valle del Cauca' },
    { muni: 'Andalucia', dept: 'Valle del Cauca' },
    { muni: 'Ansermanuevo', dept: 'Valle del Cauca' },
    { muni: 'Caicedonia', dept: 'Valle del Cauca' },
    { muni: 'Jamundi', dept: 'Valle del Cauca' },
    { muni: 'La Cumbre', dept: 'Valle del Cauca' },
    { muni: 'Palmira', dept: 'Valle del Cauca' },
    { muni: 'Roldanillo', dept: 'Valle del Cauca' },
    { muni: 'Sevilla', dept: 'Valle del Cauca' }
];

// Localidades Mayores para Ediles D.C (los 8 ediles originales)
export const EDILES_DC_LIST = [
    'USAQUÉN',
    'SAN CRISTÓBAL',
    'BOSA',
    'KENNEDY',
    'FONTIBÓN',
    'ENGATIVÁ',
    'SUBA',
    'RAFAEL URIBE'
];

// Metas oficiales de centros por cada Edil (para cálculo de multiplicador)
export const EDIL_OFFICIAL_CENTERS: Record<string, number> = {
    'USAQUÉN': 2,
    'SAN CRISTÓBAL': 2,
    'BOSA': 2,
    'KENNEDY': 4,
    'FONTIBÓN': 1,
    'ENGATIVÁ': 3,
    'SUBA': 8,
    'RAFAEL URIBE': 1
};

// Mapeo de Localidad (del Excel) a Localidad Mayor (Ediles D.C)
export const LOCALIDAD_TO_LOCALIDAD_MAYOR: Record<string, string> = {
    // Sector USAQUÉN
    'USAQUÉN': 'USAQUÉN',
    'USAQUEN': 'USAQUÉN',
    'LIJACÁ': 'USAQUÉN',
    'LIJACA': 'USAQUÉN',
    'ORQUÍDEAS': 'USAQUÉN',
    'ORQUIDEAS': 'USAQUÉN',

    // Sector SAN CRISTÓBAL
    'SAN CRISTÓBAL': 'SAN CRISTÓBAL',
    'SAN CRISTOBAL': 'SAN CRISTÓBAL',
    'EL SOSIEGO': 'SAN CRISTÓBAL',
    'LA VICTORIA': 'SAN CRISTÓBAL',

    // Sector BOSA
    'BOSA': 'BOSA',
    'BOSA LA ESTACIÓN': 'BOSA',
    'BOSA LA ESTACION': 'BOSA',
    'BOSA RECREO': 'BOSA',

    // Sector KENNEDY
    'KENNEDY': 'KENNEDY',
    'CARVAJAL': 'KENNEDY',
    'CLASS ROMA': 'KENNEDY',
    'ROMA': 'KENNEDY',
    'KENNEDY CLASS ROMA': 'KENNEDY',
    'PATIO BONITO': 'KENNEDY',
    'PATIO': 'KENNEDY',

    // Sector FONTIBÓN
    'FONTIBÓN': 'FONTIBÓN',
    'FONTIBON': 'FONTIBÓN',

    // Sector ENGATIVÁ
    'ENGATIVÁ': 'ENGATIVÁ',
    'ENGATIVA': 'ENGATIVÁ',
    'VILLA GLADYS': 'ENGATIVÁ',
    'ENGATIVÁ -VILLA GLADYS': 'ENGATIVÁ',
    'FERIAS': 'ENGATIVÁ',
    'LA GRANJA': 'ENGATIVÁ',

    // Sector SUBA
    'SUBA': 'SUBA',
    'LA COLINA': 'SUBA',
    'COLINA': 'SUBA',
    'SUBA PINAR': 'SUBA',
    'SUBA EL PINAR': 'SUBA',
    'EL PINAR': 'SUBA',
    'PINAR': 'SUBA',
    'SUBA FLORES': 'SUBA',
    'FLORES': 'SUBA',
    'SUBA FONTANAR': 'SUBA',
    'FONTANAR': 'SUBA',
    'SUBA LAS MERCEDES': 'SUBA',
    'LAS MERCEDES': 'SUBA',
    'SUBA LISBOA': 'SUBA',
    'LISBOA': 'SUBA',
    'PRADO VERANIEGO': 'SUBA',
    'SUBA PRADO': 'SUBA',
    'PRADO': 'SUBA',
    'VERANIEGO': 'SUBA',
    'SUBA RINCÓN': 'SUBA',
    'SUBA RINCON': 'SUBA',
    'RINCÓN': 'SUBA',
    'RINCON': 'SUBA',

    // Sector RAFAEL URIBE
    'RAFAEL URIBE': 'RAFAEL URIBE',
    'RAFAEL URIBE URIBE': 'RAFAEL URIBE',
    'SANTA LUCÍA': 'RAFAEL URIBE',
    'SANTA LUCIA': 'RAFAEL URIBE',

    // Otros (que no están en los 8 pero podrían aparecer)
    'USME': 'USME',
    'SANTA LIBRADA': 'USME',
    'TUNJUELITO': 'TUNJUELITO',
    'SAN VICENTE FERRER': 'TUNJUELITO',
    'PUENTE ARANDA': 'PUENTE ARANDA',
    'GALÁN': 'PUENTE ARANDA',
    'GALAN': 'PUENTE ARANDA',
    'ANTONIO NARIÑO': 'ANTONIO NARIÑO',
    'ANTONIO NARINO': 'ANTONIO NARIÑO',
    'SANTANDER': 'ANTONIO NARIÑO',
    'SANTANDER BOGOTÁ': 'ANTONIO NARIÑO',
    'CIUDAD BOLÍVAR': 'CIUDAD BOLÍVAR',
    'CIUDAD BOLIVAR': 'CIUDAD BOLÍVAR',
    'CANDELARIA LA NUEVA': 'CIUDAD BOLÍVAR',
    'TEUSAQUILLO': 'TEUSAQUILLO',
    'CHAPINERO': 'CHAPINERO',
};
